-- ======================================================
-- V1__create_personnel.sql
-- Таблиця особового складу
-- ======================================================

CREATE TABLE IF NOT EXISTS personnel (
                                         id BIGINT AUTO_INCREMENT PRIMARY KEY,
                                         personnel_number INT UNIQUE,
                                         last_name VARCHAR(255) NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    middle_name VARCHAR(255),
    rank VARCHAR(255),
    position VARCHAR(255),
    full_position VARCHAR(500),
    phone VARCHAR(255),
    note VARCHAR(500),
    active BOOLEAN DEFAULT TRUE,
    birth_date DATE,
    tax_id VARCHAR(50),
    passport_series VARCHAR(50),
    passport_number VARCHAR(50),
    blood_group VARCHAR(50),
    education VARCHAR(50),
    military_unit VARCHAR(100),
    draf_obl VARCHAR(100),
    draft_loc VARCHAR(100),
    enrollment_date DATE,
    enrollment_nakaz VARCHAR(100),
    ubd_date DATE,
    admission_nakaz VARCHAR(50),
    admission_date DATE,
    registration_address VARCHAR(500),
    living_address VARCHAR(500),
    marital_status VARCHAR(50),
    spouse_name VARCHAR(500),
    draft_date DATE,
    draft_organization VARCHAR(100),
    service_type VARCHAR(100),
    ubd_number VARCHAR(100),
    driver_license_series VARCHAR(50),
    driver_license_number VARCHAR(50),
    driver_license_category VARCHAR(100),
    family_address VARCHAR(500),
    admission_form VARCHAR(255),
    enrollment_info VARCHAR(255),
    service_for VARCHAR(100),
    shoe_size VARCHAR(10),
    uniform_size VARCHAR(10),
    headwear_size VARCHAR(10),
    vos VARCHAR(50),
    tariff_grade VARCHAR(30),
    personnel_status VARCHAR(100)
    );